version: '3'

services:
  mongodb:
    image: mongo:3.4.1
    volumes:
      - './data/db:/data/db'
    networks:
      - easy-mock
    restart: always

  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      - './data/redis:/data'
    networks:
      - easy-mock
    restart: always

  web:
    image: easymock/easymock:latest
    command: /bin/bash -c "npm run dev"
    ports:
      - 7300:7300
    volumes:
      - './logs:/home/easy-mock/east-mock/logs'
        #- './production.json:/home/easy-mock/easy-mock/config/default.json'
    networks:
      - easy-mock
    restart: always

networks:
  easy-mock:
